#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_Weather_App_maybe_full.Resource", IsApplication=true)]

namespace Android_Weather_App_maybe_full
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040002
			public const int cities = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int unit_names = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int unit_values = 2130968577;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int color_black = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int eye = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int humidity = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_refresh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int line_shape_blue = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int line_shape_green = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int line_shape_red = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int moon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int pressure = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sun = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int temperature = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int wind = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090003
			public const int descrWeather = 2131296259;
			
			// aapt resource value: 0x7f09000b
			public const int humidity = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int humidityIcon = 2131296266;
			
			// aapt resource value: 0x7f090002
			public const int imgWeather = 2131296258;
			
			// aapt resource value: 0x7f090011
			public const int moonIcon = 2131296273;
			
			// aapt resource value: 0x7f09000d
			public const int pressure = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int pressureIcon = 2131296268;
			
			// aapt resource value: 0x7f09000e
			public const int pressureStat = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int sunIcon = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int sunrise = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int sunset = 2131296274;
			
			// aapt resource value: 0x7f090001
			public const int temp = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int tempIcon = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int tempLyt = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int tempMax = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int tempMin = 2131296261;
			
			// aapt resource value: 0x7f090009
			public const int windDeg = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int windIcon = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int windSpeed = 2131296264;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070003
			public const int action_refresh = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int action_settings = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int city = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int cityName = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int hello_world = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int loc_title = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int pref_location_title = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int pref_unit_title = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int share_msg = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int summary_loc = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int summary_temp = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int temp_title = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int update = 2131165188;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int textBig = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int textSmall = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int textVerySmall = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
